version: "3"
services:
  my-container:
    image: nginx:latest
    container_name: test_nginx
    # ports:
    #   - "8110:80"
    labels:
      # 这个容器接受Host == example.com 的请求
      - traefik.http.routers.my-container.rule=Host(`example.com`)
      # Tell Traefik to use the port 12345 to connect to `my-container`
      - traefik.http.services.my-service.loadbalancer.server.port=80
  reverse-proxy:
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port 
      - "891:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8900:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data3/hongsen/traefik/lesson4/traefik.yml:/etc/traefik/traefik.yml
      - /data3/hongsen/traefik/lesson4/logs/:/var/log/
  