# Global configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Entry points
entryPoints:
  web:
    address: :80

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: true
    watch: true
api:
  insecure: true
# Logging
log:
  level: DEBUG
  filePath: /var/log/traefik.log
  
accessLog:
  filePath: /var/log/accessLog.log